[package]
name = "scah-python"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "scah"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
scah-core = { package = "scah", path = "../../scah" }
scah-ffi = { path = "../../scah-ffi" }
pyo3 = { version = "0.27.2", features = ["abi3-py310"] }
pyo3-stub-gen = "0.22.1"
