[build-system]
requires = ["maturin>=1.9.4,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["extension-module"]

[project]
name = "scah"
version = "0.0.21"
description = "CSS selectors meet streaming HTML parsing: extract exactly what you select without building a full DOM."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{ name = "Zachary McSween Manickchand", email = "contact@zacharymm.com" }]
keywords = ["html", "parser", "css", "selector", "scraping", "streaming"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Rust",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
    "Topic :: Text Processing :: Markup :: HTML",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/zacharyvmm/scah"
Repository = "https://github.com/zacharyvmm/scah"
Issues = "https://github.com/zacharyvmm/scah/issues"
Changelog = "https://github.com/zacharyvmm/scah/blob/main/CHANGELOG.md"

# uv sync --all-extras
[project.optional-dependencies]
bench = [
    "scah",
    "beautifulsoup4",
    "lxml",
    "selectolax",
    "parsel",
    "gazpacho",
    "pytest",
    "pytest-benchmark[histogram]",
    "seaborn",
    "poethepoet",
]

# uv run --all-extras poe bench
[tool.poe.tasks]
stub = { cmd = "cargo run --bin stub_gen" }
bench = [
    { ref = "stub" },
#    { cmd = "uvx maturin build --release" },
    { cmd = "uv pip install -e . --reinstall --no-cache"},
    { cmd = "pytest benches/test_synthetic.py --benchmark-columns=min,mean,max --benchmark-sort=mean --benchmark-warmup-iterations 5 --benchmark-json benches/synthetic.json" },
    { cmd = "pytest benches/test_synthetic_first.py --benchmark-columns=min,mean,max --benchmark-sort=mean --benchmark-warmup-iterations 5 --benchmark-json benches/synthetic_first.json" },
    { cmd = "pytest benches/test_spec.py --benchmark-columns=min,mean,max --benchmark-sort=mean --benchmark-warmup-iterations 5 --benchmark-json benches/whatwg.json" },
    { cmd = "pytest benches/test_structural.py --benchmark-columns=min,mean,max --benchmark-sort=mean --benchmark-warmup-iterations 5 --benchmark-json benches/nested.json" },
    { cmd = "python3 ./benches/utils/figure.py ./benches/synthetic.json -o ./benches/images/synthetic.png" },
    { cmd = "python3 ./benches/utils/figure.py ./benches/synthetic_first.json -o ./benches/images/synthetic_first.png" },
    { cmd = "python3 ./benches/utils/figure.py ./benches/whatwg.json -o ./benches/images/whatwg.png" },
    { cmd = "python3 ./benches/utils/figure.py ./benches/nested.json -o ./benches/images/nested.png" },
    { cmd = "rm ./benches/*.json" },
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
scah = { workspace = true }
