/*
 * scah C API: streaming CSS-selector-driven HTML extraction.
 *
 * Link against libscah_c (static or shared). On Linux, static linking also
 * needs -lpthread -ldl -lm.
 *
 * Workflow
 *   1. Describe a query with a ScahQueryBuilder, nesting child builders with
 *      scah_query_builder_then, and compile it with scah_query_build.
 *   2. Parse HTML against one or more queries with scah_parse.
 *   3. Look up matches with scah_store_get and scah_element_get, then read
 *      element fields with the scah_element_* getters.
 *
 * Ownership
 *   - Every handle returned through an out-pointer is owned by the caller and
 *     released with its *_free function. Every *_free function accepts NULL.
 *   - A store copies its HTML and shares its queries' selector strings, so
 *     the HTML buffer, queries, and builders may be freed as soon as
 *     scah_parse returns.
 *   - Element lists are independent of their store, but their ids are only
 *     meaningful together with the store that produced them.
 *   - String views returned by getters borrow from the store and stay valid
 *     until scah_store_free. The view returned by scah_error_message stays
 *     valid until scah_error_free.
 *   - String views are UTF-8 and are not NUL-terminated.
 *
 * Errors
 *   Fallible functions return a ScahStatus and take a trailing
 *   ScahError **out_error, which may be NULL. On entry the function sets
 *   *out_error to NULL. On failure it stores a newly allocated error there
 *   for the caller to free. Out-pointers for handles are likewise set to NULL
 *   before any work happens. Panics never unwind into C: they are reported as
 *   SCAH_STATUS_INTERNAL_PANIC.
 *
 * Threads
 *   Queries and stores are immutable and may be shared across threads.
 *   Builders, element lists, and errors must not be used from two threads at
 *   once.
 */

#ifndef SCAH_H
#define SCAH_H

/* Generated by cbindgen from crates/bindings/scah-c. Do not edit by hand. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Version of the C ABI described by `scah.h`.
 *
 * Bumped on every incompatible change to a signature, type layout, or
 * documented behavior.
 */
#define SCAH_ABI_VERSION 1

/**
 * Outcome of a fallible call.
 *
 * Any status other than `SCAH_STATUS_OK` comes with a message in
 * `*out_error` when the caller passed a non-NULL `out_error`.
 */
typedef enum ScahStatus {
  /**
   * The call succeeded.
   */
  SCAH_STATUS_OK = 0,
  /**
   * A required pointer argument was NULL, or a string view had a NULL
   * `data` pointer with a non-zero `len`.
   */
  SCAH_STATUS_NULL_POINTER = 1,
  /**
   * An input string view was not valid UTF-8.
   */
  SCAH_STATUS_INVALID_UTF8 = 2,
  /**
   * A selector could not be compiled.
   */
  SCAH_STATUS_INVALID_SELECTOR = 3,
  /**
   * `scah_parse` was called without any queries.
   */
  SCAH_STATUS_EMPTY_QUERIES = 4,
  /**
   * The HTML nests elements deeper than the parser supports.
   */
  SCAH_STATUS_MAXIMUM_DEPTH_EXCEEDED = 5,
  /**
   * An element id or attribute index was out of range.
   */
  SCAH_STATUS_INDEX_OUT_OF_BOUNDS = 6,
  /**
   * scah panicked. The library state is intact, but this is a bug worth
   * reporting.
   */
  SCAH_STATUS_INTERNAL_PANIC = 7,
} ScahStatus;

/**
 * The ids of the elements matched by one selector, in document order.
 *
 * Created by `scah_store_get` or `scah_element_get` and released with
 * `scah_element_list_free`. A list owns its ids and may outlive its store,
 * though the ids are then meaningless.
 */
typedef struct ScahElementList ScahElementList;

/**
 * An error message returned through `out_error`.
 *
 * Read it with `scah_error_message` and release it with `scah_error_free`.
 */
typedef struct ScahError ScahError;

/**
 * A compiled, immutable query.
 *
 * Created by `scah_query_build` and released with `scah_query_free`. Stores
 * keep their own reference, so a query may be freed right after parsing.
 */
typedef struct ScahQuery ScahQuery;

/**
 * A query being described: a chain of selector sections, each of which may
 * have nested child queries.
 *
 * Created by `scah_query_builder_new_all` or `scah_query_builder_new_first`
 * and released with `scah_query_builder_free`. Selectors are only compiled
 * by `scah_query_build`.
 */
typedef struct ScahQueryBuilder ScahQueryBuilder;

/**
 * The result of parsing HTML against one or more queries.
 *
 * Created by `scah_parse` and released with `scah_store_free`. The store
 * owns a copy of the HTML and shares its queries' selector strings. Every
 * string view read from it stays valid until it is freed.
 */
typedef struct ScahStore ScahStore;

/**
 * A borrowed UTF-8 string: `len` bytes starting at `data`.
 *
 * The bytes are not NUL-terminated. `data` may be NULL only when `len` is
 * zero. Views returned by this library are never NULL with a non-zero `len`.
 */
typedef struct ScahStringView {
  const uint8_t *data;
  size_t len;
} ScahStringView;

/**
 * What to keep for each element a query section matches.
 *
 * The tag name is always kept. Each field must be `true` or `false`.
 */
typedef struct ScahSave {
  /**
   * Keep the HTML between the opening and closing tags.
   */
  bool inner_html;
  /**
   * Keep the descendant text exactly as written in the source.
   */
  bool raw_text;
  /**
   * Keep the descendant text with entities decoded and whitespace
   * collapsed.
   */
  bool text;
  /**
   * Keep the `id`, `class`, and other attributes.
   */
  bool attributes;
} ScahSave;

/**
 * Identifies an element within the store that produced it.
 *
 * Ids index the store's element arena: they run from 0 to
 * `scah_store_len(store) - 1` and are only meaningful with that store.
 */
typedef size_t ScahElementId;

/**
 * A string view that may be absent.
 *
 * `is_some == false` means the value is missing; `value` is then empty.
 * `is_some == true` with `value.len == 0` means the value is an empty string.
 */
typedef struct ScahOptionalStringView {
  bool is_some;
  struct ScahStringView value;
} ScahOptionalStringView;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version of the loaded library.
 *
 * Compare against `SCAH_ABI_VERSION` to detect a header and library mismatch.
 */
uint32_t scah_abi_version(void);

/**
 * Borrow the message of `error`.
 *
 * The view stays valid until `scah_error_free(error)`. A NULL `error` yields
 * an empty view.
 *
 * # Safety
 *
 * `error` must be NULL or a live error returned by this library.
 */
struct ScahStringView scah_error_message(const struct ScahError *error);

/**
 * Free an error. NULL is ignored.
 *
 * # Safety
 *
 * `error` must be NULL or an error returned by this library that has not
 * been freed.
 */
void scah_error_free(struct ScahError *error);

/**
 * Start a query whose first section matches every element selected by
 * `selector`.
 *
 * On success `*out_builder` receives a builder to free with
 * `scah_query_builder_free`. The selector is copied and is only compiled by
 * `scah_query_build`.
 *
 * # Safety
 *
 * `selector` must be a readable view. `out_builder` and `out_error` must be
 * NULL or writable.
 */
enum ScahStatus scah_query_builder_new_all(struct ScahStringView selector,
                                           struct ScahSave save,
                                           struct ScahQueryBuilder **out_builder,
                                           struct ScahError **out_error);

/**
 * Start a query whose first section matches only the first element selected
 * by `selector`, which lets parsing stop early.
 *
 * Otherwise identical to `scah_query_builder_new_all`.
 *
 * # Safety
 *
 * Same as `scah_query_builder_new_all`.
 */
enum ScahStatus scah_query_builder_new_first(struct ScahStringView selector,
                                             struct ScahSave save,
                                             struct ScahQueryBuilder **out_builder,
                                             struct ScahError **out_error);

/**
 * Append a section that matches every element selected by `selector` inside
 * each match of the builder's last section.
 *
 * # Safety
 *
 * `builder` must be NULL or a live builder not in use elsewhere. `selector`
 * must be a readable view. `out_error` must be NULL or writable.
 */
enum ScahStatus scah_query_builder_all(struct ScahQueryBuilder *builder,
                                       struct ScahStringView selector,
                                       struct ScahSave save,
                                       struct ScahError **out_error);

/**
 * Append a section that matches only the first element selected by
 * `selector` inside each match of the builder's last section.
 *
 * # Safety
 *
 * Same as `scah_query_builder_all`.
 */
enum ScahStatus scah_query_builder_first(struct ScahQueryBuilder *builder,
                                         struct ScahStringView selector,
                                         struct ScahSave save,
                                         struct ScahError **out_error);

/**
 * Nest copies of `children` under the builder's last section.
 *
 * Each child query runs inside every match of that section, and its results
 * are read with `scah_element_get`. The children are copied, not consumed:
 * they remain owned by the caller and later changes to them do not affect
 * `builder`. A builder may be passed as its own child. `children` may be
 * NULL when `count` is zero.
 *
 * # Safety
 *
 * `builder` must be NULL or a live builder not in use elsewhere. `children`
 * must be NULL or point to `count` readable pointers, each NULL or a live
 * builder. `out_error` must be NULL or writable.
 */
enum ScahStatus scah_query_builder_then(struct ScahQueryBuilder *builder,
                                        const struct ScahQueryBuilder *const *children,
                                        size_t count,
                                        struct ScahError **out_error);

/**
 * Copy a builder, so a shared prefix can be extended in several ways.
 *
 * # Safety
 *
 * `builder` must be NULL or a live builder. `out_builder` and `out_error`
 * must be NULL or writable.
 */
enum ScahStatus scah_query_builder_clone(const struct ScahQueryBuilder *builder,
                                         struct ScahQueryBuilder **out_builder,
                                         struct ScahError **out_error);

/**
 * Free a builder. NULL is ignored.
 *
 * # Safety
 *
 * `builder` must be NULL or a builder from this library that has not been
 * freed.
 */
void scah_query_builder_free(struct ScahQueryBuilder *builder);

/**
 * Compile a builder into a query.
 *
 * The builder is left untouched and may be reused or freed. Fails with
 * `SCAH_STATUS_INVALID_SELECTOR` when any selector is invalid.
 *
 * # Safety
 *
 * `builder` must be NULL or a live builder. `out_query` and `out_error`
 * must be NULL or writable.
 */
enum ScahStatus scah_query_build(const struct ScahQueryBuilder *builder,
                                 struct ScahQuery **out_query,
                                 struct ScahError **out_error);

/**
 * Free a query. NULL is ignored. Stores parsed with it stay valid.
 *
 * # Safety
 *
 * `query` must be NULL or a query from this library that has not been
 * freed.
 */
void scah_query_free(struct ScahQuery *query);

/**
 * Parse `html` against `queries`.
 *
 * The store copies `html` and shares the selector strings of each query, so
 * both may be freed once this returns. On success `*out_store` receives a
 * store to free with `scah_store_free`.
 *
 * # Safety
 *
 * `html` must be a readable view. `queries` must be NULL or point to
 * `count` readable pointers, each NULL or a live query. `out_store` and
 * `out_error` must be NULL or writable.
 */
enum ScahStatus scah_parse(struct ScahStringView html,
                           const struct ScahQuery *const *queries,
                           size_t count,
                           struct ScahStore **out_store,
                           struct ScahError **out_error);

/**
 * Free a store. NULL is ignored.
 *
 * Invalidates every string view read from the store.
 *
 * # Safety
 *
 * `store` must be NULL or a store from this library that has not been
 * freed.
 */
void scah_store_free(struct ScahStore *store);

/**
 * The number of elements in the store, across all queries. NULL yields 0.
 *
 * # Safety
 *
 * `store` must be NULL or a live store.
 */
size_t scah_store_len(const struct ScahStore *store);

/**
 * Look up the elements matched by a top-level query section.
 *
 * `selector` must equal the selector string the section was built with. When
 * nothing matched it, or no query has such a section, this succeeds and sets
 * `*out_list` to NULL. Otherwise `*out_list` receives a non-empty list to
 * free with `scah_element_list_free`.
 *
 * # Safety
 *
 * `store` must be NULL or a live store. `selector` must be a readable view.
 * `out_list` and `out_error` must be NULL or writable.
 */
enum ScahStatus scah_store_get(const struct ScahStore *store,
                               struct ScahStringView selector,
                               struct ScahElementList **out_list,
                               struct ScahError **out_error);

/**
 * Look up the elements matched by a child query nested under `element`
 * with `scah_query_builder_then`.
 *
 * `selector` must equal the child's selector string. Like `scah_store_get`,
 * this succeeds with `*out_list` set to NULL when there are no matches.
 *
 * # Safety
 *
 * Same as `scah_store_get`.
 */
enum ScahStatus scah_element_get(const struct ScahStore *store,
                                 ScahElementId element,
                                 struct ScahStringView selector,
                                 struct ScahElementList **out_list,
                                 struct ScahError **out_error);

/**
 * The number of ids in `list`. NULL yields 0, so a missing result can be
 * treated as an empty list.
 *
 * # Safety
 *
 * `list` must be NULL or a live list.
 */
size_t scah_element_list_len(const struct ScahElementList *list);

/**
 * The ids in `list`, valid until `scah_element_list_free(list)`. NULL
 * yields NULL.
 *
 * # Safety
 *
 * `list` must be NULL or a live list.
 */
const ScahElementId *scah_element_list_ids(const struct ScahElementList *list);

/**
 * Free a list. NULL is ignored.
 *
 * # Safety
 *
 * `list` must be NULL or a list from this library that has not been freed.
 */
void scah_element_list_free(struct ScahElementList *list);

/**
 * The element's tag name.
 *
 * # Safety
 *
 * `store` must be NULL or a live store. `out_value` and `out_error` must be
 * NULL or writable.
 */
enum ScahStatus scah_element_name(const struct ScahStore *store,
                                  ScahElementId element,
                                  struct ScahStringView *out_value,
                                  struct ScahError **out_error);

/**
 * The element's `id` attribute. Missing when absent or when the query did
 * not save attributes.
 *
 * # Safety
 *
 * Same as `scah_element_name`.
 */
enum ScahStatus scah_element_id(const struct ScahStore *store,
                                ScahElementId element,
                                struct ScahOptionalStringView *out_value,
                                struct ScahError **out_error);

/**
 * The element's `class` attribute. Missing when absent or when the query
 * did not save attributes.
 *
 * # Safety
 *
 * Same as `scah_element_name`.
 */
enum ScahStatus scah_element_class_name(const struct ScahStore *store,
                                        ScahElementId element,
                                        struct ScahOptionalStringView *out_value,
                                        struct ScahError **out_error);

/**
 * The HTML between the element's tags. Missing unless the query saved
 * `inner_html`.
 *
 * # Safety
 *
 * Same as `scah_element_name`.
 */
enum ScahStatus scah_element_inner_html(const struct ScahStore *store,
                                        ScahElementId element,
                                        struct ScahOptionalStringView *out_value,
                                        struct ScahError **out_error);

/**
 * The element's descendant text as written in the source. Missing unless
 * the query saved `raw_text`.
 *
 * # Safety
 *
 * Same as `scah_element_name`.
 */
enum ScahStatus scah_element_raw_text(const struct ScahStore *store,
                                      ScahElementId element,
                                      struct ScahOptionalStringView *out_value,
                                      struct ScahError **out_error);

/**
 * The element's descendant text with entities decoded and whitespace
 * collapsed. Missing unless the query saved `text`.
 *
 * # Safety
 *
 * Same as `scah_element_name`.
 */
enum ScahStatus scah_element_text(const struct ScahStore *store,
                                  ScahElementId element,
                                  struct ScahOptionalStringView *out_value,
                                  struct ScahError **out_error);

/**
 * The value of the attribute named `key`, compared ASCII
 * case-insensitively.
 *
 * Missing when the attribute is absent, has no value (as in `<input
 * disabled>`), or the query did not save attributes. Present but empty for
 * `key=""`. Use `scah_element_attribute_at` to tell an absent attribute from
 * one without a value.
 *
 * # Safety
 *
 * `store` must be NULL or a live store. `key` must be a readable view.
 * `out_value` and `out_error` must be NULL or writable.
 */
enum ScahStatus scah_element_attribute(const struct ScahStore *store,
                                       ScahElementId element,
                                       struct ScahStringView key,
                                       struct ScahOptionalStringView *out_value,
                                       struct ScahError **out_error);

/**
 * The number of attributes saved for the element, other than `id` and
 * `class`.
 *
 * # Safety
 *
 * `store` must be NULL or a live store. `out_count` and `out_error` must be
 * NULL or writable.
 */
enum ScahStatus scah_element_attribute_count(const struct ScahStore *store,
                                             ScahElementId element,
                                             size_t *out_count,
                                             struct ScahError **out_error);

/**
 * The attribute at `index`, in source order, where `index` is below
 * `scah_element_attribute_count`.
 *
 * `*out_key` receives the name as written in the source. `*out_value` is
 * missing for an attribute without a value (as in `<input disabled>`).
 *
 * # Safety
 *
 * `store` must be NULL or a live store. `out_key`, `out_value`, and
 * `out_error` must be NULL or writable.
 */
enum ScahStatus scah_element_attribute_at(const struct ScahStore *store,
                                          ScahElementId element,
                                          size_t index,
                                          struct ScahStringView *out_key,
                                          struct ScahOptionalStringView *out_value,
                                          struct ScahError **out_error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCAH_H */
