[package]
name = "scah-reader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Streaming XML and HTML reader primitives used by scah."
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/scah-reader"

[lints.clippy]
let-and-return = "allow"
byte_char_slices = "allow"
redundant-field-names = "allow"
len_without_is_empty = "allow"
