#!/usr/bin/env python3
"""Generate the Rust lookup table from WHATWG's entities.json.

By default, generation is offline and deterministic from the committed
fixture. Pass --update-fixture to download the upstream dataset, validate it,
and update both the fixture and generated table from the same bytes. Each file
is replaced atomically, but the two-file update is not transactional.

Usage:
  python crates/scah/scripts/generate_entities.py
  python crates/scah/scripts/generate_entities.py --update-fixture
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
import unicodedata
from pathlib import Path
from urllib.request import urlopen


SCRIPT_PATH = Path(__file__).resolve()
DEFAULT_INPUT = SCRIPT_PATH.with_name("entities.json")
DESTINATION = SCRIPT_PATH.parents[1] / "src" / "html" / "entities_table.rs"
SOURCE_URL = "https://html.spec.whatwg.org/entities.json"
GENERATOR_REL = "crates/scah/scripts/generate_entities.py"
FIXTURE_REL = "crates/scah/scripts/entities.json"
LICENSE_REL = "THIRD_PARTY_LICENSES/WHATWG-HTML.txt"


def rust_string_literal(value: str) -> str:
    """Encode a Rust double-quoted string literal without UTF-16 surrogates."""
    pieces: list[str] = ['"']

    for char in value:
        code = ord(char)
        category = unicodedata.category(char)

        if char == "\\":
            pieces.append("\\\\")
        elif char == '"':
            pieces.append('\\"')
        elif char == "\n":
            pieces.append("\\n")
        elif char == "\r":
            pieces.append("\\r")
        elif char == "\t":
            pieces.append("\\t")
        elif char == "\0":
            pieces.append("\\0")
        elif code < 0x20 or code == 0x7F or category in {"Cc", "Cf", "Zl", "Zp"}:
            pieces.append(f"\\u{{{code:X}}}")
        elif category == "Zs" and code != 0x20:
            # Keep ordinary ASCII space literal; escape other Unicode spaces.
            pieces.append(f"\\u{{{code:X}}}")
        else:
            pieces.append(char)

    pieces.append('"')
    return "".join(pieces)


def read_fixture(path: Path) -> bytes:
    return path.read_bytes()


def fetch_upstream() -> bytes:
    with urlopen(SOURCE_URL) as response:
        return response.read()


def validate_source(raw: bytes) -> dict:
    source = json.loads(raw.decode("utf-8"))

    if not isinstance(source, dict):
        raise ValueError("entity source must be a JSON object")

    for name, value in source.items():
        if not isinstance(name, str):
            raise ValueError("entity names must be strings")
        if not isinstance(value, dict):
            raise ValueError(f"entity {name!r} must be an object")
        if not isinstance(value.get("characters"), str):
            raise ValueError(f"entity {name!r} has no string characters field")

    return source


def load_source(raw: bytes) -> tuple[dict, str]:
    source = validate_source(raw)
    source_hash = hashlib.sha256(raw).hexdigest()
    return source, source_hash


def _rust_u8_slice(data: bytes, indent: str = "    ") -> list[str]:
    """Format bytes as a Rust `[u8; N] = [..]` body (one byte per element)."""
    lines: list[str] = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        body = ", ".join(f"0x{byte:02X}" for byte in chunk)
        lines.append(f"{indent}{body},")
    return lines


def generate_table(source: dict, source_hash: str) -> str:
    """Emit a relocation-free entity table stored entirely in `.rodata`.

    Pointer-pair tables (`[(&str, &str); N]`) force per-entry dynamic
    relocations into `.data`/`.data.rel.ro` (~70KiB). That bloat changes
    process image layout and measurably slows no-text parses that never
    decode entities. Offsets into byte blobs avoid those relocations.
    """
    entries = sorted(
        (name.removeprefix("&"), value["characters"]) for name, value in source.items()
    )
    name_blob = bytearray()
    value_blob = bytearray()
    name_ends: list[int] = []
    value_ends: list[int] = []
    for name, value in entries:
        name_blob.extend(name.encode("utf-8"))
        name_ends.append(len(name_blob))
        value_blob.extend(value.encode("utf-8"))
        value_ends.append(len(value_blob))

    if name_ends and name_ends[-1] > 0xFFFF_FFFF:
        raise ValueError("entity name blob exceeds u32 range")
    if value_ends and value_ends[-1] > 0xFFFF_FFFF:
        raise ValueError("entity value blob exceeds u32 range")

    lines = [
        f"// @generated by {GENERATOR_REL}; do not edit.",
        f"// Source: {SOURCE_URL}",
        f"// Source SHA-256: {source_hash}",
        f"// Entry count: {len(entries)}",
        f"// Fixture: {FIXTURE_REL}",
        f"// Third-party license: {LICENSE_REL}",
        "//",
        "// Layout: sorted names/values as raw UTF-8 blobs plus exclusive-end",
        "// offset tables. Kept relocation-free so no-text binaries do not pay",
        "// for a large relocated `.data` entity image.",
        "",
        f"pub(super) const MAX_NAME_LEN: usize = {max(len(name) for name, _ in entries)};",
        f"pub(super) const NAMED_ENTITY_COUNT: usize = {len(entries)};",
        "",
        f"pub(super) static ENTITY_NAMES: [u8; {len(name_blob)}] = [",
    ]
    lines.extend(_rust_u8_slice(bytes(name_blob)))
    lines.append("];")
    lines.append("")
    lines.append(f"pub(super) static ENTITY_VALUES: [u8; {len(value_blob)}] = [")
    lines.extend(_rust_u8_slice(bytes(value_blob)))
    lines.append("];")
    lines.append("")
    lines.append(
        f"pub(super) static ENTITY_NAME_ENDS: [u32; {len(name_ends)}] = ["
    )
    for offset in range(0, len(name_ends), 8):
        chunk = name_ends[offset : offset + 8]
        lines.append("    " + ", ".join(str(value) for value in chunk) + ",")
    lines.append("];")
    lines.append("")
    lines.append(
        f"pub(super) static ENTITY_VALUE_ENDS: [u32; {len(value_ends)}] = ["
    )
    for offset in range(0, len(value_ends), 8):
        chunk = value_ends[offset : offset + 8]
        lines.append("    " + ", ".join(str(value) for value in chunk) + ",")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def generate_from_bytes(raw: bytes) -> str:
    source, source_hash = load_source(raw)
    table = generate_table(source, source_hash)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        suffix=".rs",
        delete=False,
    ) as handle:
        handle.write(table)
        temporary = Path(handle.name)
    try:
        rustfmt_file(temporary)
        return temporary.read_text(encoding="utf-8")
    finally:
        temporary.unlink(missing_ok=True)


def rustfmt_file(path: Path) -> None:
    """Format `path` with rustfmt so CI `cargo fmt --check` stays green."""
    import shutil
    import subprocess

    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        raise RuntimeError("rustfmt is required to regenerate entities_table.rs")
    subprocess.run([rustfmt, str(path)], check=True)


def atomic_write_text(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=destination.parent,
        prefix=f".{destination.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(destination)
    rustfmt_file(destination)


def atomic_write_bytes(destination: Path, content: bytes) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="wb",
        dir=destination.parent,
        prefix=f".{destination.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(destination)


def update_fixture(
    fixture_path: Path = DEFAULT_INPUT,
    table_path: Path = DESTINATION,
    raw: bytes | None = None,
) -> None:
    """Download (or accept) upstream bytes and replace fixture + table together."""
    previous_fixture = fixture_path.read_bytes() if fixture_path.exists() else None
    previous_table = table_path.read_text(encoding="utf-8") if table_path.exists() else None

    if raw is None:
        raw = fetch_upstream()
    table = generate_from_bytes(raw)
    source_hash = hashlib.sha256(raw).hexdigest()
    entry_count = len(validate_source(raw))

    # Validate and generate first; then write fixture, then table.
    try:
        atomic_write_bytes(fixture_path, raw)
    except OSError as exc:
        raise SystemExit(f"failed to write fixture {fixture_path}: {exc}") from exc

    try:
        atomic_write_text(table_path, table)
    except OSError as exc:
        raise SystemExit(
            f"wrote fixture {fixture_path} but failed to write table {table_path}: {exc}\n"
            "Rerun with --update-fixture to restore consistency."
        ) from exc

    fixture_changed = previous_fixture != raw
    table_changed = previous_table != table
    print(f"wrote {fixture_path}")
    print(f"wrote {table_path}")
    print(f"source sha-256: {source_hash}")
    print(f"entry count: {entry_count}")
    print(f"fixture changed: {fixture_changed}")
    print(f"table changed: {table_changed}")


def self_test() -> None:
    expected = {
        "plain": '"plain"',
        'quote: "': '"quote: \\""',
        "slash: \\": '"slash: \\\\"',
        "\u0001": '"\\u{1}"',
        "\n": '"\\n"',
        "\r": '"\\r"',
        "\t": '"\\t"',
        "\0": '"\\0"',
        "\u007f": '"\\u{7F}"',
        "\u00a0": '"\\u{A0}"',
        "\u2061": '"\\u{2061}"',
        "\u2028": '"\\u{2028}"',
        "\u2029": '"\\u{2029}"',
        "𝔄": '"𝔄"',
        "\u2242\u0338": '"\u2242\u0338"',
    }
    for value, want in expected.items():
        got = rust_string_literal(value)
        if got != want:
            raise AssertionError(f"rust_string_literal({value!r}) = {got!r}, want {want!r}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Path to entities.json (default: committed fixture beside this script)",
    )
    parser.add_argument(
        "--update-fixture",
        action="store_true",
        help=(
            f"Download {SOURCE_URL} and update the committed fixture and generated "
            "Rust table from the same validated bytes"
        ),
    )
    parser.add_argument(
        "--fetch",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run escaping self-tests and exit",
    )
    args = parser.parse_args(argv)

    if args.self_test:
        self_test()
        print("self-test ok")
        return 0

    if args.fetch:
        print(
            "--fetch has been replaced by --update-fixture because fetching must update\n"
            "both the committed source fixture and generated Rust table.",
            file=sys.stderr,
        )
        return 2

    if args.update_fixture:
        update_fixture(fixture_path=args.input, table_path=DESTINATION)
        return 0

    raw = read_fixture(args.input)
    source, source_hash = load_source(raw)
    content = generate_table(source, source_hash)
    atomic_write_text(DESTINATION, content)
    print(f"wrote {DESTINATION}")
    print(f"source sha-256: {source_hash}")
    print(f"entry count: {len(source)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
