[package]
name = "scah-ffi"
version = "0.0.21"
edition = "2024"
license = "MIT"
repository = "https://github.com/zacharyvmm/scah"
publish = false

[lib]
name = "scah_ffi"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
scah = { path = "../scah" }

[dev-dependencies]
pretty_assertions = "1.4.1"
