/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsQuery {
  toString(): string
}

export declare class Query {
  static all(selector: string, save: Save): QueryBuilder
  static first(selector: string, save: Save): QueryBuilder
}
export type JsQueryStatic = Query

export declare class QueryBuilder {
  all(selector: string, save: Save): QueryBuilder
  first(selector: string, save: Save): QueryBuilder
  then(callback: (arg: JsQueryFactory) => Array<QueryBuilder>): QueryBuilder
  build(): JsQuery
}
export type JsQueryBuilder = QueryBuilder

export declare class QueryFactory {
  all(selector: string, save: Save): QueryBuilder
  first(selector: string, save: Save): QueryBuilder
}
export type JsQueryFactory = QueryFactory

export declare class Store {
  get(index: number): Element | null
  get length(): number
}
export type JSStore = Store

export interface Element {
  name: Buffer
  class?: Buffer
  id?: Buffer
  attributes: Array<[Buffer, Buffer | undefined | null]>
  innerHtml?: Buffer
  textContent?: Buffer
  children: Array<[Buffer, Array<number>]>
}

export declare function parse(html: Buffer, queries: Array<JsQuery>): Store

export interface Save {
  innerHtml: boolean
  textContent: boolean
}
