/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Element {

}
export type JSElement = Element

export declare class Query {
  static all(selector: string): Query
}
export type JSQuery = Query

export declare class Store {

}
export type JSStore = Store

export declare function parse(html: Buffer, queries: Array<Query>): Store
