/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Query {
  static all(selector: string): Query
}
export type JSQuery = Query

export declare class Store {
  get(index: number): Element | null
}
export type JSStore = Store

export interface Element {
  name: Buffer
  class?: Buffer
  id?: Buffer
  attributes: Array<[Buffer, Buffer | undefined | null]>
  innerHtml?: Buffer
  textContent?: Buffer
  children: Array<[Buffer, Array<number>]>
}

export declare function parse(html: Buffer, queries: Array<Query>): Store
