[package]
name = "scah"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "CSS selectors meet streaming HTML parsing: extract exactly what you select without building a full DOM."
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/scah"
readme = "../../README.md"
keywords = ["css", "selector", "parser", "html", "sax"]
categories = ["parser-implementations", "web-programming"]
exclude = [
    "scripts/**",
]

[lib]
name = "scah"
path = "src/lib.rs"

[dependencies]
smallvec = "1.15.1"
scah-reader.workspace = true
scah-query-ir.workspace = true
scah-macros.workspace = true
tracing = { version = "0.1", optional = true }

[features]
default = []
bench-internals = []
simd-bench-internals = []
otel = ["dep:tracing"]

[[example]]
name = "cursor_stats"
required-features = ["bench-internals"]

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints.clippy]
let-and-return = "allow"
byte_char_slices = "allow"
redundant-field-names = "allow"
len_without_is_empty = "allow"
