/* scah C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef SCAH_H
#define SCAH_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

// Result status for every fallible C ABI function.
typedef enum ScahStatus {
  ScahStatus_Ok = 0,
  ScahStatus_NullPointer = 1,
  ScahStatus_InvalidUtf8 = 2,
  ScahStatus_InvalidSelector = 3,
  ScahStatus_EmptyQueries = 4,
  ScahStatus_MaximumDepthExceeded = 5,
  ScahStatus_InvalidSection = 6,
  ScahStatus_IndexOutOfBounds = 7,
  ScahStatus_InternalPanic = 8,
  // Caller-provided buffer capacity is insufficient.
  ScahStatus_BufferTooSmall = 9,
} ScahStatus;

// Opaque list of element ids sharing a store.
//
// Match results are stored as a linked-list span (`first` + `len`) rather than
// an eagerly copied ID vector. [`scah_element_list_fill_ids`] and
// [`scah_store_get_ids_fill`] copy IDs into a caller buffer. [`scah_element_list_ids`]
// lazily materializes a cache on first use for C callers that need a borrowed
// pointer.
//
// # Lifetime invariants
//
// - [`scah_element_list_ids`] returns a pointer into this list's lazily
//   materialized ID cache. The pointer remains valid until the list is freed.
// - String views obtained via element getters remain valid while this list
//   (which retains the [`OwnedStore`]) remains alive.
// - Freeing the original [`ScahStore`] does not invalidate elements accessed
//   through this list.
// - An element ID may only be used with this list, or a descendant list
//   returned from [`scah_element_get`] on an element from this owner.
typedef struct ScahElementList ScahElementList;

// Owned diagnostic message allocated by the FFI layer.
typedef struct ScahError ScahError;

// Opaque compiled query handle.
typedef struct ScahQuery ScahQuery;

// Opaque pending query builder handle.
typedef struct ScahQueryBuilder ScahQueryBuilder;

// Opaque parsed store handle.
typedef struct ScahStore ScahStore;

// A non-owning UTF-8 string view (`pointer` + `length`).
//
// Never requires a NUL terminator. A null `data` pointer is only valid when
// `len == 0`.
typedef struct ScahStringView {
  const uint8_t *data;
  size_t len;
} ScahStringView;

// Which content to capture for matched elements.
typedef struct ScahSave {
  uint8_t inner_html;
  uint8_t text_content;
} ScahSave;

// Section identifier within a query builder tree.
typedef size_t ScahQuerySectionId;

// Store-local element identifier.
//
// An element ID may only be used with the [`ScahElementList`] that produced
// it, or a descendant list returned from an element belonging to the same
// owner. Not a heap handle. Do not exchange IDs between arbitrary lists even
// when they happen to share a store.
typedef size_t ScahElementId;

// Optional string view. Distinguish missing values from empty strings with
// `is_some` rather than overloading null pointers.
//
// - `is_some == 0`: value is absent (`None`)
// - `is_some != 0` with `value.len == 0`: explicitly empty string (`Some("")`)
typedef struct ScahOptionalStringView {
  struct ScahStringView value;
  uint8_t is_some;
} ScahOptionalStringView;

// Fixed-field snapshot of an element. All string views borrow store-owned HTML
// and remain valid while the element-list owner remains alive.
typedef struct ScahElementView {
  struct ScahStringView name;
  struct ScahOptionalStringView id;
  struct ScahOptionalStringView class_name;
  struct ScahOptionalStringView inner_html;
  struct ScahOptionalStringView text_content;
  size_t attribute_count;
} ScahElementView;

// Borrowed key/value view for one attribute.
typedef struct ScahAttributeView {
  struct ScahStringView key;
  struct ScahOptionalStringView value;
} ScahAttributeView;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Borrow the error message. Valid while `error` remains alive.
//
// # Safety
//
// `error` must either be null or point to a live [`ScahError`] returned by
// scah-ffi that has not yet been freed. The returned view borrows the error's
// message and is only valid until the error is freed or mutated.
struct ScahStringView scah_error_message(const struct ScahError *error);

// Free an error handle. Null is a no-op.
//
// # Safety
//
// A non-null `error` must have been returned by scah-ffi, must not already
// have been freed, and must not be used again after this call.
void scah_error_free(struct ScahError *error);

// Create a root builder that matches all occurrences of `selector`.
//
// The selector is not validated until [`scah_query_builder_build`].
//
// # Safety
//
// `selector` must satisfy [`ScahStringView::as_str`]. `out_builder` must be
// non-null and valid for writing one `*mut ScahQueryBuilder`. When
// `out_error` is non-null, it must be valid for writing one `*mut ScahError`.
// On success the caller owns the returned builder and must free it with
// [`scah_query_builder_free`].
enum ScahStatus scah_query_all(struct ScahStringView selector,
                               struct ScahSave save,
                               struct ScahQueryBuilder **out_builder,
                               struct ScahError **out_error);

// Create a root builder that matches the first occurrence of `selector`.
//
// # Safety
//
// Same requirements as [`scah_query_all`].
enum ScahStatus scah_query_first(struct ScahStringView selector,
                                 struct ScahSave save,
                                 struct ScahQueryBuilder **out_builder,
                                 struct ScahError **out_error);

// Append a linear `all` child under the builder's current last section.
//
// # Safety
//
// `builder` must point to a live [`ScahQueryBuilder`]. `selector` must satisfy
// [`ScahStringView::as_str`]. When `out_error` is non-null, it must be valid
// for writing one `*mut ScahError`.
enum ScahStatus scah_query_builder_all(struct ScahQueryBuilder *builder,
                                       struct ScahStringView selector,
                                       struct ScahSave save,
                                       struct ScahError **out_error);

// Append a linear `first` child under the builder's current last section.
//
// # Safety
//
// Same requirements as [`scah_query_builder_all`].
enum ScahStatus scah_query_builder_first(struct ScahQueryBuilder *builder,
                                         struct ScahStringView selector,
                                         struct ScahSave save,
                                         struct ScahError **out_error);

// Return the current (last) section id for subsequent [`scah_query_builder_append`] calls.
//
// # Safety
//
// `builder` must either be null (returns [`ScahStatus::NullPointer`]) or point
// to a live [`ScahQueryBuilder`]. `out_section` must be non-null and valid for
// writing one [`ScahQuerySectionId`]. When `out_error` is non-null, it must be
// valid for writing one `*mut ScahError`.
enum ScahStatus scah_query_builder_current_section(const struct ScahQueryBuilder *builder,
                                                   ScahQuerySectionId *out_section,
                                                   struct ScahError **out_error);

// Clone `child` under `parent` without consuming either builder.
//
// Section IDs are append tokens, not permanent random-access mutation
// handles. An append is valid when `parent` is the builder's current last
// section, or the active append parent established by a prior append in the
// same append group (as used by consecutive `.then()` sibling branches).
// Linear `all` / `first` mutations clear the active append parent. A stale
// section ID that is neither the current last section nor the active append
// parent returns [`ScahStatus::InvalidSection`] and leaves the builder
// unmodified.
//
// Self-append (`builder == child`) clones the current tree into an owned
// temporary before taking a mutable borrow of `builder`, so overlapping
// Rust references are never created.
//
// # Safety
//
// `builder` must point to a live mutable [`ScahQueryBuilder`]. `child` must
// point to a live [`ScahQueryBuilder`]. When `out_error` is non-null, it must
// be valid for writing one `*mut ScahError`.
enum ScahStatus scah_query_builder_append(struct ScahQueryBuilder *builder,
                                          ScahQuerySectionId parent,
                                          const struct ScahQueryBuilder *child,
                                          struct ScahError **out_error);

// Compile the builder into a query. Does not consume the builder.
//
// # Safety
//
// `builder` must point to a live [`ScahQueryBuilder`]. `out_query` must be
// non-null and valid for writing one `*mut ScahQuery`. When `out_error` is
// non-null, it must be valid for writing one `*mut ScahError`. On success the
// caller owns the returned query and must free it with [`scah_query_free`].
enum ScahStatus scah_query_builder_build(const struct ScahQueryBuilder *builder,
                                         struct ScahQuery **out_query,
                                         struct ScahError **out_error);

// Deep-clone a builder handle.
//
// # Safety
//
// `builder` must point to a live [`ScahQueryBuilder`]. `out_builder` must be
// non-null and valid for writing one `*mut ScahQueryBuilder`. When `out_error`
// is non-null, it must be valid for writing one `*mut ScahError`. On success
// the caller owns the clone and must free it with [`scah_query_builder_free`].
enum ScahStatus scah_query_builder_clone(const struct ScahQueryBuilder *builder,
                                         struct ScahQueryBuilder **out_builder,
                                         struct ScahError **out_error);

// Free a builder handle. Null is a no-op.
//
// # Safety
//
// A non-null `builder` must have been returned by scah-ffi, must not already
// have been freed, and must not be used again after this call.
void scah_query_builder_free(struct ScahQueryBuilder *builder);

// Free a query handle. Null is a no-op.
//
// # Safety
//
// A non-null `query` must have been returned by scah-ffi, must not already
// have been freed, and must not be used again after this call.
void scah_query_free(struct ScahQuery *query);

// Current C ABI version.
uint32_t scah_abi_version(void);

// Parse HTML against one or more compiled queries.
//
// Returned string views from the store/elements borrow store-owned HTML and
// remain valid only while the owning store or element-list handle is alive.
//
// # Safety
//
// `html` must satisfy [`ScahStringView::as_str`] and remain valid for the
// duration of this call. When `query_count > 0`, `queries` must point to an
// array of `query_count` readable query-handle pointers; every entry must
// point to a live [`ScahQuery`]. `out_store` must be non-null and valid for
// writing one `*mut ScahStore`. When `out_error` is non-null, it must be valid
// for writing one `*mut ScahError`. On success the caller owns the store and
// must free it with [`scah_store_free`].
enum ScahStatus scah_parse(struct ScahStringView html,
                           const struct ScahQuery *const *queries,
                           size_t query_count,
                           struct ScahStore **out_store,
                           struct ScahError **out_error);

// Number of elements in the store.
//
// # Safety
//
// `store` must either be null or point to a live [`ScahStore`] returned by
// scah-ffi. `out_len`, when non-null, must be valid for writing one `usize`.
// When `out_error` is non-null, it must be valid for writing one
// `*mut ScahError`.
enum ScahStatus scah_store_len(const struct ScahStore *store,
                               size_t *out_len,
                               struct ScahError **out_error);

// Look up elements matched by `query`.
//
// When the selector is absent, `*out_found` is set to 0 and this is not an error.
// The returned list stores a match span (`first` + `len`) rather than an
// eagerly copied ID vector. Use [`scah_element_list_fill_ids`] or
// [`scah_store_get_ids_fill`] to copy IDs into a caller buffer.
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. `query` must satisfy
// [`ScahStringView::as_str`]. `out_elements` and `out_found` must be non-null
// and valid for writing. When `out_error` is non-null, it must be valid for
// writing one `*mut ScahError`. On success with `*out_found == 1`, the caller
// owns the list and must free it with [`scah_element_list_free`].
enum ScahStatus scah_store_get(const struct ScahStore *store,
                               struct ScahStringView query,
                               struct ScahElementList **out_elements,
                               uint8_t *out_found,
                               struct ScahError **out_error);

// Create a store-retaining owner list with an empty span.
//
// Language bindings allocate one owner per parsed store and reuse it for all
// element getters, avoiding a boxed list allocation on every lookup. Prefer
// [`scah_store_get_span`] + [`scah_store_fill_ids`] for result materialization.
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. `out_owner` must be non-null.
// On success the caller owns the list and must free it with
// [`scah_element_list_free`].
enum ScahStatus scah_store_owner(const struct ScahStore *store,
                                 struct ScahElementList **out_owner,
                                 struct ScahError **out_error);

// Look up match span metadata without allocating a result list.
//
// On success with `*out_found == 1`, writes the first element id and the
// match count (O(1) after query-node resolution). No owned outputs are
// transferred.
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. `out_first`, `out_len`, and
// `out_found` must be non-null.
enum ScahStatus scah_store_get_span(const struct ScahStore *store,
                                    struct ScahStringView query,
                                    ScahElementId *out_first,
                                    size_t *out_len,
                                    uint8_t *out_found,
                                    struct ScahError **out_error);

// Copy `len` result IDs starting at `first` into a caller buffer.
//
// When `capacity < len`, returns [`ScahStatus::BufferTooSmall`] with
// `*out_written = len` and no diagnostic allocation.
// When the supplied span is invalid or ends early, returns
// [`ScahStatus::IndexOutOfBounds`] with `*out_written` set to the number of
// valid prefix IDs copied.
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. When `capacity > 0`, `out_ids`
// must be writable for `capacity` IDs. `out_written` must be non-null.
enum ScahStatus scah_store_fill_ids(const struct ScahStore *store,
                                    ScahElementId first,
                                    size_t len,
                                    ScahElementId *out_ids,
                                    size_t capacity,
                                    size_t *out_written,
                                    struct ScahError **out_error);

// Copy `len` result IDs starting at `first` using a list owner's store.
//
// Same sizing contract as [`scah_store_fill_ids`].
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. When `capacity > 0`,
// `out_ids` must be writable for `capacity` IDs. `out_written` must be non-null.
enum ScahStatus scah_element_list_fill_from(const struct ScahElementList *owner,
                                            ScahElementId first,
                                            size_t len,
                                            ScahElementId *out_ids,
                                            size_t capacity,
                                            size_t *out_written,
                                            struct ScahError **out_error);

// Look up matches and copy IDs (and optionally names) into caller buffers.
//
// When `capacity` is smaller than the match count, returns
// [`ScahStatus::BufferTooSmall`] and writes the required count to
// `*out_written`. No owned list is transferred and no [`ScahError`] is
// allocated for this expected capacity negotiation — use [`scah_store_get`]
// then [`scah_element_list_fill_ids`] when the caller needs a list owner.
//
// Pass `out_elements == NULL` to only fill IDs (caller must keep the store
// alive for subsequent element access). Pass `out_names == NULL` to skip
// name materialization; when non-null it must have `capacity` slots.
//
// Owned outputs are transferred only when status is [`ScahStatus::Ok`].
//
// # Safety
//
// Same string/store requirements as [`scah_store_get`]. When `capacity > 0`,
// `out_ids` must point to a writable array of `capacity` IDs. `out_written`
// and `out_found` must be non-null.
enum ScahStatus scah_store_get_ids_fill(const struct ScahStore *store,
                                        struct ScahStringView query,
                                        ScahElementId *out_ids,
                                        struct ScahStringView *out_names,
                                        size_t capacity,
                                        size_t *out_written,
                                        struct ScahElementList **out_elements,
                                        uint8_t *out_found,
                                        struct ScahError **out_error);

// Free a store handle. Null is a no-op.
//
// # Safety
//
// A non-null `store` must have been returned by scah-ffi, must not already
// have been freed, and must not be used again after this call. Element-list
// handles that retain an `Arc` to the same store remain valid.
void scah_store_free(struct ScahStore *store);

// Length of an element list.
//
// # Safety
//
// `list` must either be null or point to a live [`ScahElementList`].
// `out_len`, when non-null, must be valid for writing one `usize`. When
// `out_error` is non-null, it must be valid for writing one `*mut ScahError`.
enum ScahStatus scah_element_list_len(const struct ScahElementList *list,
                                      size_t *out_len,
                                      struct ScahError **out_error);

// Fill a caller-provided buffer with the list's element IDs.
//
// When `capacity` is smaller than the list length, returns
// [`ScahStatus::BufferTooSmall`] and writes the required count to
// `*out_written`.
//
// # Safety
//
// `list` must point to a live [`ScahElementList`]. When `capacity > 0`,
// `out_ids` must point to a writable array of `capacity` IDs. `out_written`
// must be non-null.
enum ScahStatus scah_element_list_fill_ids(const struct ScahElementList *list,
                                           ScahElementId *out_ids,
                                           size_t capacity,
                                           size_t *out_written,
                                           struct ScahError **out_error);

// Borrow the complete ID slice for a result list.
//
// Lazily materializes an ID cache on first call. Prefer
// [`scah_element_list_fill_ids`] or [`scah_store_get_ids_fill`] to avoid the
// cache allocation. The returned pointer remains valid until the list is freed.
//
// # Safety
//
// `list` must point to a live [`ScahElementList`]. `out_ids` and `out_len` must
// be non-null and valid for writing. When `out_error` is non-null, it must be
// valid for writing one `*mut ScahError`. The pointer written to `*out_ids`
// borrows the list and must not be used after [`scah_element_list_free`].
enum ScahStatus scah_element_list_ids(const struct ScahElementList *list,
                                      const ScahElementId **out_ids,
                                      size_t *out_len,
                                      struct ScahError **out_error);

// Free an element list. Null is a no-op.
//
// # Safety
//
// A non-null `list` must have been returned by scah-ffi, must not already
// have been freed, and must not be used again after this call.
void scah_element_list_free(struct ScahElementList *list);

// Element tag name. Borrowed from store-owned HTML.
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. `element` must be a
// bounds-valid store element id. `out_name` must be non-null and valid for
// writing one [`ScahStringView`]. The returned view is valid only while
// `owner` remains alive. When `out_error` is non-null, it must be valid for
// writing one `*mut ScahError`.
enum ScahStatus scah_element_name(const struct ScahElementList *owner,
                                  ScahElementId element,
                                  struct ScahStringView *out_name,
                                  struct ScahError **out_error);

// Fill tag names for many element IDs in one call.
//
// Writes `count` borrowed name views into `out_names`. Prefer this over
// repeated [`scah_element_name`] when materializing a large result list.
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. `ids` and `out_names` must
// each be valid for `count` elements. Returned views remain valid while
// `owner` remains alive.
enum ScahStatus scah_element_names_fill(const struct ScahElementList *owner,
                                        const ScahElementId *ids,
                                        size_t count,
                                        struct ScahStringView *out_names,
                                        struct ScahError **out_error);

// Element `id` attribute, if present.
//
// # Safety
//
// Same owner/element requirements as [`scah_element_name`]. `out_id` must be
// non-null. Returned string data is valid only while `owner` remains alive.
enum ScahStatus scah_element_id(const struct ScahElementList *owner,
                                ScahElementId element,
                                struct ScahOptionalStringView *out_id,
                                struct ScahError **out_error);

// Element `class` attribute, if present.
//
// # Safety
//
// Same requirements as [`scah_element_id`].
enum ScahStatus scah_element_class_name(const struct ScahElementList *owner,
                                        ScahElementId element,
                                        struct ScahOptionalStringView *out_class,
                                        struct ScahError **out_error);

// Element inner HTML, if captured.
//
// # Safety
//
// Same requirements as [`scah_element_id`].
enum ScahStatus scah_element_inner_html(const struct ScahElementList *owner,
                                        ScahElementId element,
                                        struct ScahOptionalStringView *out_html,
                                        struct ScahError **out_error);

// Element text content, if captured.
//
// # Safety
//
// Same requirements as [`scah_element_id`].
enum ScahStatus scah_element_text_content(const struct ScahElementList *owner,
                                          ScahElementId element,
                                          struct ScahOptionalStringView *out_text,
                                          struct ScahError **out_error);

// Fixed-field element snapshot in one ABI call.
//
// # Safety
//
// Same owner/element requirements as [`scah_element_name`]. `out_view` must be
// non-null. All string views remain valid while `owner` remains alive.
enum ScahStatus scah_element_view(const struct ScahElementList *owner,
                                  ScahElementId element,
                                  struct ScahElementView *out_view,
                                  struct ScahError **out_error);

// Look up a single attribute by name.
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. `key` must satisfy
// [`ScahStringView::as_str`]. `out_value` must be non-null. Returned string
// data is valid only while `owner` remains alive.
enum ScahStatus scah_element_get_attribute(const struct ScahElementList *owner,
                                           ScahElementId element,
                                           struct ScahStringView key,
                                           struct ScahOptionalStringView *out_value,
                                           struct ScahError **out_error);

// Number of extra attributes (excluding dedicated class/id fields).
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. `out_count` must be
// non-null and valid for writing one `usize`.
enum ScahStatus scah_element_attribute_count(const struct ScahElementList *owner,
                                             ScahElementId element,
                                             size_t *out_count,
                                             struct ScahError **out_error);

// Indexed attribute access without building a hash map.
//
// Distinguishes missing attribute values from explicitly empty ones:
//
// - `out_value.is_some == 0`: attribute had no value (`None`)
// - `out_value.is_some != 0` with `out_value.value.len == 0`: explicitly empty (`Some("")`)
//
// # Safety
//
// Same owner/element requirements as [`scah_element_name`]. `out_key` and
// `out_value` must be non-null. Returned string data is valid only while
// `owner` remains alive.
enum ScahStatus scah_element_attribute_at(const struct ScahElementList *owner,
                                          ScahElementId element,
                                          size_t index,
                                          struct ScahStringView *out_key,
                                          struct ScahOptionalStringView *out_value,
                                          struct ScahError **out_error);

// Fill a caller-provided buffer with borrowed attribute views.
//
// When `capacity` is smaller than the attribute count, returns
// [`ScahStatus::BufferTooSmall`] and writes the required count to
// `*out_written` when that pointer is non-null.
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. When `capacity > 0`,
// `out_attributes` must point to a writable array of `capacity`
// [`ScahAttributeView`] values. `out_written` must be non-null. Returned
// string data is valid only while `owner` remains alive.
enum ScahStatus scah_element_attributes_fill(const struct ScahElementList *owner,
                                             ScahElementId element,
                                             struct ScahAttributeView *out_attributes,
                                             size_t capacity,
                                             size_t *out_written,
                                             struct ScahError **out_error);

// Nested query lookup on an element.
//
// When the child query is absent, `*out_found` is 0 (not an error).
//
// # Safety
//
// `owner` must point to a live [`ScahElementList`]. `query` must satisfy
// [`ScahStringView::as_str`]. `out_elements` and `out_found` must be non-null
// and valid for writing. On success with `*out_found == 1`, the caller owns
// the child list and must free it with [`scah_element_list_free`]. The child
// list retains its own store `Arc`.
enum ScahStatus scah_element_get(const struct ScahElementList *owner,
                                 ScahElementId element,
                                 struct ScahStringView query,
                                 struct ScahElementList **out_elements,
                                 uint8_t *out_found,
                                 struct ScahError **out_error);

// Nested lookup that returns span metadata without allocating a child list.
//
// # Safety
//
// Same owner/element/query requirements as [`scah_element_get`]. `out_first`,
// `out_len`, and `out_found` must be non-null.
enum ScahStatus scah_element_get_span(const struct ScahElementList *owner,
                                      ScahElementId element,
                                      struct ScahStringView query,
                                      ScahElementId *out_first,
                                      size_t *out_len,
                                      uint8_t *out_found,
                                      struct ScahError **out_error);

// Nested lookup that copies child IDs into a caller buffer in one pass.
//
// # Safety
//
// Same requirements as [`scah_element_get`]. When `capacity > 0`, `out_ids`
// must be writable for `capacity` IDs. `out_written` and `out_found` must be
// non-null.
enum ScahStatus scah_element_get_ids_fill(const struct ScahElementList *owner,
                                          ScahElementId element,
                                          struct ScahStringView query,
                                          ScahElementId *out_ids,
                                          size_t capacity,
                                          size_t *out_written,
                                          struct ScahElementList **out_elements,
                                          uint8_t *out_found,
                                          struct ScahError **out_error);

// Element tag name via store handle (no result-list owner required).
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. `element` must be a bounds-valid
// store element id. `out_name` must be non-null and valid for writing one
// [`ScahStringView`]. The returned view is valid only while `store` remains
// alive. When `out_error` is non-null, it must be valid for writing one
// `*mut ScahError`.
enum ScahStatus scah_store_element_name(const struct ScahStore *store,
                                        ScahElementId element,
                                        struct ScahStringView *out_name,
                                        struct ScahError **out_error);

// Element `id` attribute via store handle.
//
// # Safety
//
// Same store/element requirements as [`scah_store_element_name`]. `out_id`
// must be non-null. Returned string data is valid only while `store` remains
// alive.
enum ScahStatus scah_store_element_id(const struct ScahStore *store,
                                      ScahElementId element,
                                      struct ScahOptionalStringView *out_id,
                                      struct ScahError **out_error);

// Element `class` attribute via store handle.
//
// # Safety
//
// Same requirements as [`scah_store_element_id`].
enum ScahStatus scah_store_element_class_name(const struct ScahStore *store,
                                              ScahElementId element,
                                              struct ScahOptionalStringView *out_class,
                                              struct ScahError **out_error);

// Element inner HTML via store handle.
//
// # Safety
//
// Same requirements as [`scah_store_element_id`].
enum ScahStatus scah_store_element_inner_html(const struct ScahStore *store,
                                              ScahElementId element,
                                              struct ScahOptionalStringView *out_html,
                                              struct ScahError **out_error);

// Element text content via store handle.
//
// # Safety
//
// Same requirements as [`scah_store_element_id`].
enum ScahStatus scah_store_element_text_content(const struct ScahStore *store,
                                                ScahElementId element,
                                                struct ScahOptionalStringView *out_text,
                                                struct ScahError **out_error);

// Look up a single attribute by name via store handle.
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. `key` must satisfy
// [`ScahStringView::as_str`]. `out_value` must be non-null. Returned string
// data is valid only while `store` remains alive.
enum ScahStatus scah_store_element_get_attribute(const struct ScahStore *store,
                                                 ScahElementId element,
                                                 struct ScahStringView key,
                                                 struct ScahOptionalStringView *out_value,
                                                 struct ScahError **out_error);

// Fill extra attributes via store handle.
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. When `capacity > 0`,
// `out_attributes` must point to a writable array of `capacity`
// [`ScahAttributeView`] values. `out_written` must be non-null. Returned
// string data is valid only while `store` remains alive.
enum ScahStatus scah_store_element_attributes_fill(const struct ScahStore *store,
                                                   ScahElementId element,
                                                   struct ScahAttributeView *out_attributes,
                                                   size_t capacity,
                                                   size_t *out_written,
                                                   struct ScahError **out_error);

// Nested lookup via store handle (no child list allocation).
//
// # Safety
//
// `store` must point to a live [`ScahStore`]. `query` must satisfy
// [`ScahStringView::as_str`]. When `capacity > 0`, `out_ids` must be writable
// for `capacity` IDs. `out_written` and `out_found` must be non-null.
enum ScahStatus scah_store_element_get_ids_fill(const struct ScahStore *store,
                                                ScahElementId element,
                                                struct ScahStringView query,
                                                ScahElementId *out_ids,
                                                size_t capacity,
                                                size_t *out_written,
                                                uint8_t *out_found,
                                                struct ScahError **out_error);

// Fixed-field element snapshot via store handle.
//
// # Safety
//
// Same store/element requirements as [`scah_store_element_name`]. `out_view`
// must be non-null. All string views remain valid while `store` remains alive.
enum ScahStatus scah_store_element_view(const struct ScahStore *store,
                                        ScahElementId element,
                                        struct ScahElementView *out_view,
                                        struct ScahError **out_error);

// Capture neither inner HTML nor text content.
struct ScahSave scah_save_none(void);

// Capture both inner HTML and text content.
struct ScahSave scah_save_all(void);

// Capture only inner HTML.
struct ScahSave scah_save_only_inner_html(void);

// Capture only text content.
struct ScahSave scah_save_only_text_content(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCAH_H */
