[package]
name = "scah-query-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Internal query IR used by the scah selector and macro crates."
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/scah-query-ir"

[dependencies]
smallvec = "1.15.1"
scah-reader.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints.clippy]
let-and-return = "allow"
byte_char_slices = "allow"
redundant-field-names = "allow"
len_without_is_empty = "allow"
