
[package]
name = "scah-nodejs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = "3.0.0"
napi-derive = "3.0.0"

  [dependencies.scah]
  workspace = true

[build-dependencies]
napi-build = "2"
