/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Element {
  toJson(): JsonElement
  get name(): string | null
  get className(): string | null
  get id(): string | null
  getAttribute(key: string): string | null
  get attributes(): object
  get innerHtml(): string | null
  get textContent(): string | null
  get(query: string): Array<Element>
}
export type JsElement = Element

export declare class JsQuery {}

export declare class Query {
  static all(selector: string, save?: Save | undefined | null): QueryBuilder
  static first(selector: string, save?: Save | undefined | null): QueryBuilder
}
export type JsQueryStatic = Query

export declare class QueryBuilder {
  all(selector: string, save?: Save | undefined | null): QueryBuilder
  first(selector: string, save?: Save | undefined | null): QueryBuilder
  then(callback: (arg: JsQueryFactory) => Array<QueryBuilder>): QueryBuilder
  build(): JsQuery
}
export type JsQueryBuilder = QueryBuilder

export declare class QueryFactory {
  all(selector: string, save?: Save | undefined | null): QueryBuilder
  first(selector: string, save?: Save | undefined | null): QueryBuilder
}
export type JsQueryFactory = QueryFactory

export declare class Store {
  get(query: string): Array<JsElement> | null
  get length(): number
}
export type JSStore = Store

export interface JsonElement {
  name: string
  id?: string
  class?: string
  attributes: object
  innerHtml?: string
  textContent?: string
}

export declare function parse(html: string, queries: Array<JsQuery>): Store

export interface Save {
  innerHtml?: boolean
  textContent?: boolean
}
